/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  containsBytes,
  getU8Encoder,
  type Address,
  type ReadonlyUint8Array,
} from '@solana/web3.js';
import {
  type ParsedDeployInstruction,
  type ParsedFinalizeInstruction,
  type ParsedRetractInstruction,
  type ParsedTransferAuthorityInstruction,
  type ParsedTruncateInstruction,
  type ParsedWriteInstruction,
} from '../instructions';

export const SOLANA_LOADER_V4_PROGRAM_PROGRAM_ADDRESS =
  'CoreBPFLoaderV41111111111111111111111111111' as Address<'CoreBPFLoaderV41111111111111111111111111111'>;

export enum SolanaLoaderV4ProgramInstruction {
  Write,
  Truncate,
  Deploy,
  Retract,
  TransferAuthority,
  Finalize,
}

export function identifySolanaLoaderV4ProgramInstruction(
  instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array
): SolanaLoaderV4ProgramInstruction {
  const data = 'data' in instruction ? instruction.data : instruction;
  if (containsBytes(data, getU8Encoder().encode(0), 0)) {
    return SolanaLoaderV4ProgramInstruction.Write;
  }
  if (containsBytes(data, getU8Encoder().encode(1), 0)) {
    return SolanaLoaderV4ProgramInstruction.Truncate;
  }
  if (containsBytes(data, getU8Encoder().encode(2), 0)) {
    return SolanaLoaderV4ProgramInstruction.Deploy;
  }
  if (containsBytes(data, getU8Encoder().encode(3), 0)) {
    return SolanaLoaderV4ProgramInstruction.Retract;
  }
  if (containsBytes(data, getU8Encoder().encode(4), 0)) {
    return SolanaLoaderV4ProgramInstruction.TransferAuthority;
  }
  if (containsBytes(data, getU8Encoder().encode(5), 0)) {
    return SolanaLoaderV4ProgramInstruction.Finalize;
  }
  throw new Error(
    'The provided instruction could not be identified as a solanaLoaderV4Program instruction.'
  );
}

export type ParsedSolanaLoaderV4ProgramInstruction<
  TProgram extends string = 'CoreBPFLoaderV41111111111111111111111111111',
> =
  | ({
      instructionType: SolanaLoaderV4ProgramInstruction.Write;
    } & ParsedWriteInstruction<TProgram>)
  | ({
      instructionType: SolanaLoaderV4ProgramInstruction.Truncate;
    } & ParsedTruncateInstruction<TProgram>)
  | ({
      instructionType: SolanaLoaderV4ProgramInstruction.Deploy;
    } & ParsedDeployInstruction<TProgram>)
  | ({
      instructionType: SolanaLoaderV4ProgramInstruction.Retract;
    } & ParsedRetractInstruction<TProgram>)
  | ({
      instructionType: SolanaLoaderV4ProgramInstruction.TransferAuthority;
    } & ParsedTransferAuthorityInstruction<TProgram>)
  | ({
      instructionType: SolanaLoaderV4ProgramInstruction.Finalize;
    } & ParsedFinalizeInstruction<TProgram>);
