/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  isProgramError,
  type Address,
  type SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM,
  type SolanaError,
} from '@solana/web3.js';
import { VERIFIER_ROUTER_PROGRAM_ADDRESS } from '../programs';

/** InvalidProofOfExploit: Invalid proof of exploit */
export const VERIFIER_ROUTER_ERROR__INVALID_PROOF_OF_EXPLOIT = 0x1770; // 6000

export type VerifierRouterError =
  typeof VERIFIER_ROUTER_ERROR__INVALID_PROOF_OF_EXPLOIT;

let verifierRouterErrorMessages:
  | Record<VerifierRouterError, string>
  | undefined;
if (process.env.NODE_ENV !== 'production') {
  verifierRouterErrorMessages = {
    [VERIFIER_ROUTER_ERROR__INVALID_PROOF_OF_EXPLOIT]: `Invalid proof of exploit`,
  };
}

export function getVerifierRouterErrorMessage(
  code: VerifierRouterError
): string {
  if (process.env.NODE_ENV !== 'production') {
    return (verifierRouterErrorMessages as Record<VerifierRouterError, string>)[
      code
    ];
  }

  return 'Error message not available in production bundles.';
}

export function isVerifierRouterError<
  TProgramErrorCode extends VerifierRouterError,
>(
  error: unknown,
  transactionMessage: {
    instructions: Record<number, { programAddress: Address }>;
  },
  code?: TProgramErrorCode
): error is SolanaError<typeof SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM> &
  Readonly<{ context: Readonly<{ code: TProgramErrorCode }> }> {
  return isProgramError<TProgramErrorCode>(
    error,
    transactionMessage,
    VERIFIER_ROUTER_PROGRAM_ADDRESS,
    code
  );
}
