/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type TransactionSigner,
  type WritableAccount,
} from '@solana/kit';
import { SOLANA_LOADER_V3_PROGRAM_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const CLOSE_DISCRIMINATOR = 5;

export function getCloseDiscriminatorBytes() {
  return getU32Encoder().encode(CLOSE_DISCRIMINATOR);
}

export type CloseInstruction<
  TProgram extends string = typeof SOLANA_LOADER_V3_PROGRAM_PROGRAM_ADDRESS,
  TAccountBufferOrProgramDataAccount extends
    | string
    | IAccountMeta<string> = string,
  TAccountDestinationAccount extends string | IAccountMeta<string> = string,
  TAccountAuthority extends string | IAccountMeta<string> = string,
  TAccountProgramAccount extends string | IAccountMeta<string> = string,
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountBufferOrProgramDataAccount extends string
        ? WritableAccount<TAccountBufferOrProgramDataAccount>
        : TAccountBufferOrProgramDataAccount,
      TAccountDestinationAccount extends string
        ? WritableAccount<TAccountDestinationAccount>
        : TAccountDestinationAccount,
      TAccountAuthority extends string
        ? ReadonlySignerAccount<TAccountAuthority> &
            IAccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      TAccountProgramAccount extends string
        ? ReadonlyAccount<TAccountProgramAccount>
        : TAccountProgramAccount,
      ...TRemainingAccounts,
    ]
  >;

export type CloseInstructionData = { discriminator: number };

export type CloseInstructionDataArgs = {};

export function getCloseInstructionDataEncoder(): Encoder<CloseInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', getU32Encoder()]]),
    (value) => ({ ...value, discriminator: CLOSE_DISCRIMINATOR })
  );
}

export function getCloseInstructionDataDecoder(): Decoder<CloseInstructionData> {
  return getStructDecoder([['discriminator', getU32Decoder()]]);
}

export function getCloseInstructionDataCodec(): Codec<
  CloseInstructionDataArgs,
  CloseInstructionData
> {
  return combineCodec(
    getCloseInstructionDataEncoder(),
    getCloseInstructionDataDecoder()
  );
}

export type CloseInput<
  TAccountBufferOrProgramDataAccount extends string = string,
  TAccountDestinationAccount extends string = string,
  TAccountAuthority extends string = string,
  TAccountProgramAccount extends string = string,
> = {
  /** Buffer or ProgramData account to close. */
  bufferOrProgramDataAccount: Address<TAccountBufferOrProgramDataAccount>;
  /** Destination account for reclaimed lamports. */
  destinationAccount: Address<TAccountDestinationAccount>;
  /** Authority (optional). */
  authority?: TransactionSigner<TAccountAuthority>;
  /** Program account (optional). */
  programAccount?: Address<TAccountProgramAccount>;
};

export function getCloseInstruction<
  TAccountBufferOrProgramDataAccount extends string,
  TAccountDestinationAccount extends string,
  TAccountAuthority extends string,
  TAccountProgramAccount extends string,
  TProgramAddress extends
    Address = typeof SOLANA_LOADER_V3_PROGRAM_PROGRAM_ADDRESS,
>(
  input: CloseInput<
    TAccountBufferOrProgramDataAccount,
    TAccountDestinationAccount,
    TAccountAuthority,
    TAccountProgramAccount
  >,
  config?: { programAddress?: TProgramAddress }
): CloseInstruction<
  TProgramAddress,
  TAccountBufferOrProgramDataAccount,
  TAccountDestinationAccount,
  TAccountAuthority,
  TAccountProgramAccount
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? SOLANA_LOADER_V3_PROGRAM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    bufferOrProgramDataAccount: {
      value: input.bufferOrProgramDataAccount ?? null,
      isWritable: true,
    },
    destinationAccount: {
      value: input.destinationAccount ?? null,
      isWritable: true,
    },
    authority: { value: input.authority ?? null, isWritable: false },
    programAccount: { value: input.programAccount ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.bufferOrProgramDataAccount),
      getAccountMeta(accounts.destinationAccount),
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.programAccount),
    ],
    programAddress,
    data: getCloseInstructionDataEncoder().encode({}),
  } as CloseInstruction<
    TProgramAddress,
    TAccountBufferOrProgramDataAccount,
    TAccountDestinationAccount,
    TAccountAuthority,
    TAccountProgramAccount
  >;

  return instruction;
}

export type ParsedCloseInstruction<
  TProgram extends string = typeof SOLANA_LOADER_V3_PROGRAM_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Buffer or ProgramData account to close. */
    bufferOrProgramDataAccount: TAccountMetas[0];
    /** Destination account for reclaimed lamports. */
    destinationAccount: TAccountMetas[1];
    /** Authority (optional). */
    authority?: TAccountMetas[2] | undefined;
    /** Program account (optional). */
    programAccount?: TAccountMetas[3] | undefined;
  };
  data: CloseInstructionData;
};

export function parseCloseInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>
): ParsedCloseInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 4) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  const getNextOptionalAccount = () => {
    const accountMeta = getNextAccount();
    return accountMeta.address === SOLANA_LOADER_V3_PROGRAM_PROGRAM_ADDRESS
      ? undefined
      : accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      bufferOrProgramDataAccount: getNextAccount(),
      destinationAccount: getNextAccount(),
      authority: getNextOptionalAccount(),
      programAccount: getNextOptionalAccount(),
    },
    data: getCloseInstructionDataDecoder().decode(instruction.data),
  };
}
