/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getArrayDecoder,
  getArrayEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  type Codec,
  type Decoder,
  type Encoder,
  type ReadonlyUint8Array,
} from '@solana/web3.js';

export type Proof = {
  piA: ReadonlyUint8Array;
  piB: Array<number>;
  piC: ReadonlyUint8Array;
};

export type ProofArgs = Proof;

export function getProofEncoder(): Encoder<ProofArgs> {
  return getStructEncoder([
    ['piA', fixEncoderSize(getBytesEncoder(), 64)],
    ['piB', getArrayEncoder(getU8Encoder(), { size: 128 })],
    ['piC', fixEncoderSize(getBytesEncoder(), 64)],
  ]);
}

export function getProofDecoder(): Decoder<Proof> {
  return getStructDecoder([
    ['piA', fixDecoderSize(getBytesDecoder(), 64)],
    ['piB', getArrayDecoder(getU8Decoder(), { size: 128 })],
    ['piC', fixDecoderSize(getBytesDecoder(), 64)],
  ]);
}

export function getProofCodec(): Codec<ProofArgs, Proof> {
  return combineCodec(getProofEncoder(), getProofDecoder());
}
