/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { VERIFIER_ROUTER_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const TRANSFER_OWNERSHIP_DISCRIMINATOR = new Uint8Array([
  65, 177, 215, 73, 53, 45, 99, 47,
]);

export function getTransferOwnershipDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    TRANSFER_OWNERSHIP_DISCRIMINATOR
  );
}

export type TransferOwnershipInstruction<
  TProgram extends string = typeof VERIFIER_ROUTER_PROGRAM_ADDRESS,
  TAccountState extends string | IAccountMeta<string> = string,
  TAccountAuthority extends string | IAccountMeta<string> = string,
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountState extends string
        ? WritableAccount<TAccountState>
        : TAccountState,
      TAccountAuthority extends string
        ? WritableSignerAccount<TAccountAuthority> &
            IAccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      ...TRemainingAccounts,
    ]
  >;

export type TransferOwnershipInstructionData = {
  discriminator: ReadonlyUint8Array;
  newOwner: Address;
};

export type TransferOwnershipInstructionDataArgs = { newOwner: Address };

export function getTransferOwnershipInstructionDataEncoder(): Encoder<TransferOwnershipInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['newOwner', getAddressEncoder()],
    ]),
    (value) => ({ ...value, discriminator: TRANSFER_OWNERSHIP_DISCRIMINATOR })
  );
}

export function getTransferOwnershipInstructionDataDecoder(): Decoder<TransferOwnershipInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['newOwner', getAddressDecoder()],
  ]);
}

export function getTransferOwnershipInstructionDataCodec(): Codec<
  TransferOwnershipInstructionDataArgs,
  TransferOwnershipInstructionData
> {
  return combineCodec(
    getTransferOwnershipInstructionDataEncoder(),
    getTransferOwnershipInstructionDataDecoder()
  );
}

export type TransferOwnershipInput<
  TAccountState extends string = string,
  TAccountAuthority extends string = string,
> = {
  state: Address<TAccountState>;
  authority: TransactionSigner<TAccountAuthority>;
  newOwner: TransferOwnershipInstructionDataArgs['newOwner'];
};

export function getTransferOwnershipInstruction<
  TAccountState extends string,
  TAccountAuthority extends string,
  TProgramAddress extends Address = typeof VERIFIER_ROUTER_PROGRAM_ADDRESS,
>(
  input: TransferOwnershipInput<TAccountState, TAccountAuthority>,
  config?: { programAddress?: TProgramAddress }
): TransferOwnershipInstruction<
  TProgramAddress,
  TAccountState,
  TAccountAuthority
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? VERIFIER_ROUTER_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    state: { value: input.state ?? null, isWritable: true },
    authority: { value: input.authority ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.state),
      getAccountMeta(accounts.authority),
    ],
    programAddress,
    data: getTransferOwnershipInstructionDataEncoder().encode(
      args as TransferOwnershipInstructionDataArgs
    ),
  } as TransferOwnershipInstruction<
    TProgramAddress,
    TAccountState,
    TAccountAuthority
  >;

  return instruction;
}

export type ParsedTransferOwnershipInstruction<
  TProgram extends string = typeof VERIFIER_ROUTER_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    state: TAccountMetas[0];
    authority: TAccountMetas[1];
  };
  data: TransferOwnershipInstructionData;
};

export function parseTransferOwnershipInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>
): ParsedTransferOwnershipInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      state: getNextAccount(),
      authority: getNextAccount(),
    },
    data: getTransferOwnershipInstructionDataDecoder().decode(instruction.data),
  };
}
