/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlySignerAccount,
  type TransactionSigner,
  type WritableAccount,
} from '@solana/web3.js';
import { SOLANA_LOADER_V4_PROGRAM_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const TRANSFER_AUTHORITY_DISCRIMINATOR = 4;

export function getTransferAuthorityDiscriminatorBytes() {
  return getU8Encoder().encode(TRANSFER_AUTHORITY_DISCRIMINATOR);
}

export type TransferAuthorityInstruction<
  TProgram extends string = typeof SOLANA_LOADER_V4_PROGRAM_PROGRAM_ADDRESS,
  TAccountProgram extends string | IAccountMeta<string> = string,
  TAccountCurrentAuthority extends string | IAccountMeta<string> = string,
  TAccountNewAuthority extends string | IAccountMeta<string> = string,
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountProgram extends string
        ? WritableAccount<TAccountProgram>
        : TAccountProgram,
      TAccountCurrentAuthority extends string
        ? ReadonlySignerAccount<TAccountCurrentAuthority> &
            IAccountSignerMeta<TAccountCurrentAuthority>
        : TAccountCurrentAuthority,
      TAccountNewAuthority extends string
        ? ReadonlySignerAccount<TAccountNewAuthority> &
            IAccountSignerMeta<TAccountNewAuthority>
        : TAccountNewAuthority,
      ...TRemainingAccounts,
    ]
  >;

export type TransferAuthorityInstructionData = { discriminator: number };

export type TransferAuthorityInstructionDataArgs = {};

export function getTransferAuthorityInstructionDataEncoder(): Encoder<TransferAuthorityInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', getU8Encoder()]]),
    (value) => ({ ...value, discriminator: TRANSFER_AUTHORITY_DISCRIMINATOR })
  );
}

export function getTransferAuthorityInstructionDataDecoder(): Decoder<TransferAuthorityInstructionData> {
  return getStructDecoder([['discriminator', getU8Decoder()]]);
}

export function getTransferAuthorityInstructionDataCodec(): Codec<
  TransferAuthorityInstructionDataArgs,
  TransferAuthorityInstructionData
> {
  return combineCodec(
    getTransferAuthorityInstructionDataEncoder(),
    getTransferAuthorityInstructionDataDecoder()
  );
}

export type TransferAuthorityInput<
  TAccountProgram extends string = string,
  TAccountCurrentAuthority extends string = string,
  TAccountNewAuthority extends string = string,
> = {
  /** Program account to change the authority of. */
  program: Address<TAccountProgram>;
  /** Current program authority. */
  currentAuthority: TransactionSigner<TAccountCurrentAuthority>;
  /** New program authority. */
  newAuthority: TransactionSigner<TAccountNewAuthority>;
};

export function getTransferAuthorityInstruction<
  TAccountProgram extends string,
  TAccountCurrentAuthority extends string,
  TAccountNewAuthority extends string,
  TProgramAddress extends
    Address = typeof SOLANA_LOADER_V4_PROGRAM_PROGRAM_ADDRESS,
>(
  input: TransferAuthorityInput<
    TAccountProgram,
    TAccountCurrentAuthority,
    TAccountNewAuthority
  >,
  config?: { programAddress?: TProgramAddress }
): TransferAuthorityInstruction<
  TProgramAddress,
  TAccountProgram,
  TAccountCurrentAuthority,
  TAccountNewAuthority
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? SOLANA_LOADER_V4_PROGRAM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    program: { value: input.program ?? null, isWritable: true },
    currentAuthority: {
      value: input.currentAuthority ?? null,
      isWritable: false,
    },
    newAuthority: { value: input.newAuthority ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.program),
      getAccountMeta(accounts.currentAuthority),
      getAccountMeta(accounts.newAuthority),
    ],
    programAddress,
    data: getTransferAuthorityInstructionDataEncoder().encode({}),
  } as TransferAuthorityInstruction<
    TProgramAddress,
    TAccountProgram,
    TAccountCurrentAuthority,
    TAccountNewAuthority
  >;

  return instruction;
}

export type ParsedTransferAuthorityInstruction<
  TProgram extends string = typeof SOLANA_LOADER_V4_PROGRAM_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Program account to change the authority of. */
    program: TAccountMetas[0];
    /** Current program authority. */
    currentAuthority: TAccountMetas[1];
    /** New program authority. */
    newAuthority: TAccountMetas[2];
  };
  data: TransferAuthorityInstructionData;
};

export function parseTransferAuthorityInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>
): ParsedTransferAuthorityInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      program: getNextAccount(),
      currentAuthority: getNextAccount(),
      newAuthority: getNextAccount(),
    },
    data: getTransferAuthorityInstructionDataDecoder().decode(instruction.data),
  };
}
